"""empty message

Revision ID: 9e4c66338d58
Revises: 9be7a950c10a
Create Date: 2023-11-23 01:08:48.944186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e4c66338d58'
down_revision = '9be7a950c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrent_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('deposit', 'expense', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('frequency', sa.Enum('weekly', 'monthly', name='recurrent_frequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_transaction', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('deposit', 'expense', name='category_type'),
               type_=sa.Enum('deposit', 'expense', name='transaction_type'),
               existing_nullable=False,
               server_default='deposit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('deposit', 'expense', name='transaction_type'),
               type_=postgresql.ENUM('deposit', 'expense', name='category_type'),
               existing_nullable=False,
               server_default='deposit')

    op.drop_table('recurrent_transaction')
    # ### end Alembic commands ###
